---
<% if fog_file = File.expand_path('~/.fog') and File.exists?(fog_file)
  fog_file = YAML.load_file(fog_file)
  ENV['AWS_ACCESS_KEY_ID'] ||= fog_file.fetch('travis-ci', {})['aws_access_key_id']
  ENV['AWS_SECRET_ACCESS_KEY'] ||= fog_file.fetch('travis-ci', {})['aws_secret_access_key']
  ENV['AWS_KEYPAIR_NAME'] ||= fog_file.fetch('travis-ci', {})['aws_keypair_name']
  ENV['EC2_SSH_KEY_PATH'] ||= File.expand_path('~/.ssh/id_rsa_kitchen_ec2')
end %>
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  require_chef_omnibus: "11.4.4"
provisioner:
  name: chef_solo
  attributes:
    deploy: {}
    ssh_users: {}
    opsworks_rubygems:
      version: "2.2.2"
    opsworks_bundler:
      version: "1.5.3"
      manage_package: null
    opsworks:
      agent_version: "33300020141216163306"
      activity: "execute_recipes"
      valid_client_activities:
        - "reboot"
        - "stop"
        - "deploy"
        - "setup"
        - "configure"
        - "update_dependencies"
        - "install_dependencies"
        - "update_custom_cookbooks"
        - "execute_recipes"
      sent_at: 1418924612
      deployment: "f14b3f61-4feb-47bd-9f28-828911841b71"
      layers:
        test:
          name: "test"
          id: "35e86b84-6f42-442c-8727-198fe1b03670"
          elb-load-balancers: []
          instances:
            test1:
              public_dns_name: "127.0.0.1"
              private_dns_name: "127.0.0.1"
              backends: 8
              ip: "127.0.0.1"
              private_ip: "127.0.0.1"
              instance_type: "c3.large"
              status: "online"
              id: "bee7ca44-e8d9-4d27-8e92-cddacdddf95c"
              aws_instance_id: "i-foobar"
              elastic_ip: null
              created_at: "2014-12-18T17:37:56+00:00"
              booted_at: "2014-12-18T17:38:50+00:00"
              region: "us-east-1"
              availability_zone: "us-east-1b"
              infrastructure_class: "ec2"
      applications: []
      stack:
        name: "test"
        id: "e5dcd258-3af7-4f88-9ae3-84bd9bd924d8"
        vpc_id: "vpc-foobar"
        elb-load-balancers: []
        rds_instances: []
      instance:
        id: "bee7ca44-e8d9-4d27-8e92-cddacdddf95c"
        hostname: "test1"
        instance_type: "c3.large"
        public_dns_name: "127.0.0.1"
        private_dns_name: "127.0.0.1"
        ip: "127.0.0.1"
        private_ip: "127.0.0.1"
        architecture: "x86_64"
        layers:
          - "test"
        backends: 8
        aws_instance_id: "i-foobar"
        region: "us-east-1"
        availability_zone: "us-east-1b"
        subnet_id: "subnet-foobar"
        infrastructure_class: "ec2"
      ruby_version: "2.0.0"
      ruby_stack: "ruby"
      rails_stack:
        name: null
    opsworks_custom_cookbooks:
      enabled: false
      recipes:
        - "opsworks_stack_state_sync"
        - "ssh_users"
        - "test_suite"
        - "opsworks_cleanup"
    chef_environment: "_default"
    opsworks_commons:
      assets_url: "https://opsworks-instance-assets-us-east-1.s3.amazonaws.com"

platforms:
  - name: ec2
    driver_plugin: ec2
    driver_config:
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
      username: ec2-user
      flavor_id: c3.large
      image_id: ami-0268d56a
      region: us-east-1
      availability_zone: us-east-1b
      security_group_ids: ['ci-testing']
      interface: public
      tags:
        Name: <%= "#{ENV['CI'] ? 'travis-ci' : ENV['USER']}-opsworks-kitchen-compatibility" %>
        Env: public

suites:
  - name: ruby-193
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[ssh_host_keys]
      - recipe[ssh_users]
      - recipe[mysql::client]
      - recipe[dependencies]
      - recipe[ebs]
      - recipe[opsworks_ganglia::client]
    attributes:
      opsworks:
        ruby_version: 1.9.3
  - name: ruby-200
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[ssh_host_keys]
      - recipe[ssh_users]
      - recipe[mysql::client]
      - recipe[dependencies]
      - recipe[ebs]
      - recipe[opsworks_ganglia::client]
    attributes:
      opsworks:
        ruby_version: 2.0.0
  - name: ruby-21
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[ssh_host_keys]
      - recipe[ssh_users]
      - recipe[mysql::client]
      - recipe[dependencies]
      - recipe[ebs]
      - recipe[opsworks_ganglia::client]
    attributes:
      opsworks:
        ruby_version: 2.1