env:
  global:
  - EC2_SSH_KEY_PATH: id_rsa_kitchen_ec2
  - secure: Y/XdBRm0PvFm51xg1bRr2DQO05QhYG6D2+y+WBd/7XVkCQ9yZ/xGxBf5Z+0THkruM13EJ+Llmsl3iGLKmaygRpw8MlX7zshrvXmJNKHyTH0GBZ2/POEvnR4Ge2H7fo2qtM82XobhGCvUpnCYMrPxj8W3jBcFaM/RZH+kPc744pU=
  - secure: e5/BBqjAXARSN4NXYBply/gJtxSqsIWwChfjZ8iD31Pe9xamfuRwt7247s4dFCiL4op6nke+XPRVwMVzw+9JzS0fyHBjsCzmowXruRDO2B0/lIek+GPgVAbN9qeyHRwBTX5ErfPCsNTXCI5oK0okONgAkx7xtYRR3ieCYS8vYeI=
  - secure: iMGUyWCHIoRoOUFNlgugvhnIm2fX6jJO7Qg97Bk3616cHTX+gh64fYiEEIAKrOB69U6F25fpetDBMwhw2WX8WnyAHbkUhW6ySItBx8KhrgVEk2hN88nOM5iped+LNrejjM6cWRyZHV/UmoJu4Ha6P1qicCfOP4Dp8Viggi+VxN4=
before_install:
- openssl aes-256-cbc -K $encrypted_1f4c965b8c54_key -iv $encrypted_1f4c965b8c54_iv
  -in id_rsa_kitchen_ec2.enc -out id_rsa_kitchen_ec2 -d
- chmod 600 id_rsa_kitchen_ec2
script: bundle exec kitchen test -d always
language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
